core-linux/src/Handler.cpp
As per https://github.com/neutralinojs/neutralinojs/issues/47, removing the debug log messages.
Was able to built the `core-linux` successfully:
```
bash build.sh 
Neutralino is being built..
```
And run it [http://localhost:8080/myapp]:
=> Removing debugging log messages

CODE_OF_CONDUCT.md
Updates code of conduct email address to neutralinojs@gmail.com.
Closes #58
=> Update code of conduct email

README.md
Replaces `neutralinojs.github.io` links in readme with `neutralino.js.org` in readme.
Closes #57
=> Replace neutralinojs.github.io links in readme

core-linux/build.sh, core-shared/log.cpp, core-shared/log.h, core-windows/build.bat
Signed-off-by: Philipp Ludwig <git@philippludwig.net>
This PR adds log file support; as suggested in #167, this will log everything to file called `neutralinojs.log`. Logging to the file and to stdout can be disabled, both is enabled by default.
To realize this, I used the standard C++ filesystem library. If neutralinojs gets ever upgraded to C++17, you should replace the `std::experimental::filesystem` with just `std::filesystem`.
The existing logging class is extended with the described feature.
No tests required, since this is fairly simple.
None.
On Windows, the lines of the log file will end with `\r\n` to provide better support with default Windows tools such as notepad.
=> Add log file support, implement #167.

core-macos/example/Neut.app/Contents/Info.plist
This will prevent the app looking fuzzy in a HiDPI/Retina environment on macOS.
Add `NSHighResolutionCapable` to `Info.plist` file
Open the bundle on a HiDPI macOS desktop or see the screenshots above
None.
None.
=> Add HighResolution capability for macOS

core-linux/src/settings.cpp, core-macos/src/settings.cpp, core-windows/src/settings.cpp
Update the value of NL_VERSION to match the app version.
Just the global var in s
Use the NL_VERSION variable in a script,.
I suggest that in the future there be a single source file for setting all the non-OS-specific script constants like NL_VERSION to use.
=> Update NL_VERSION to 1.2.0

core-linux/build.sh
fix output name in the linux build shell script
- fixed typo
it is just a typo in the neutralino build script for linux.
None.
None.
=> fix output name in prompt

.github/workflows/cpp_ci.yml, README.md, build.sh, core-macos/build.sh
add shell script to build core-macos and njs for macos build. Fixes #215 
- as stated in the description above
- This uses the original build.sh in the root directory. Just type bash build.sh linux to build linux build or bash build.sh macos to build macos version
None.
Only macos debug build is supported for this PR
=> Macos automated build using shell script

core-windows/src/functions.cpp, core-windows/src/functions.h, core-windows/src/router.cpp
This is a fix for bug #159.
No special character including spaces is decoded for now in routing. This lays to the default route returning `{"message":"Neutralino"}`.
My solution is to [decode paths](https://en.wikipedia.org/wiki/Percent-encoding) before routing.
=> fix url encoding in routes

core-shared/webview/webview.h
Since Neutralino apps are local apps, they should be able to paste.
```html
<div>
<h2>Clipboard Test</h2>
<input id='output' />
<input id='paste' type='button' value='paste' />
<input id='copy' type='button' value='copy' />
<script>
var $ = x => document.querySelector(x)
var out = $("#output")
$('#paste').onclick = () => {
out.focus()
out.select()
document.execCommand("paste")
}
$('#copy').onclick = () => {
out.select()
document.execCommand("copy")
}
</script>
</div>
```
=> allow access to clipboard

api/app/app.cpp, api/computer/computer.cpp, api/os/os.cpp, build_freebsd.sh, lib/tray/tray.h
To build neutralino on FreeBSD, install the following packages
```
pkg install -y gtk+-3.0 webkit2gtk-4.0 glib-2.0 appindicator3-0.1
sh build_freebsd.sh
```
=> Fix more missing features for FreeBSD

server/ping.cpp
Removed an unused interval parameter. No references anywhere in the codebase, seems like it was added in error.
- Removed the interval parameter in the function declaration.
- Removed the "10000" parameter in the function call.
- Check if the pinging system still works?
None.
None.
=> Removed unused interval parameter

lib/webview/webview.h
The failure is caused by the fact that SetProcessDpiAwarenessContext function
does not exist in older windows before windows 10.
This fix is merely avoiding calling the function if it does not exist in user32.dll.
Ultimate fix should include calling equivalent functions in older windows.
- check the existance of the function and call it if available.  Ignore otherwise.
- split the logic into separate method.  So that it can be extended to support
older Windows in future.
=> #486: Call SetProcessDpiAwarenessContext only when available

buildzri.config.json
Currently, building on Windows litters the project root with temporary object files. While this is not a problem as object files are ignored, it is slightly annoying to work with when using VS Code.
- Add the `/Fobin/` flag to Windows build options. This puts the object files in the `bin/` folder.
- Run build using `python scripts/bz.py`. All temporary object files should be in `bin/`.
None.
None.
=> Prevent cluttering of root folder when building on Windows

.github/workflows/test_suite.yml, scripts/bz.py
Currently, the checkout action only fetches a single commit. When the tests run on a branch other than main, then build fails the as `git log ...` command in `bz.py` cannot find the main branch locally (as it does not exist on the CI machine).
This can be seen in:
- https://github.com/neutralinojs/neutralinojs/runs/6112616322?check_suite_focus=true
- https://github.com/neutralinojs/neutralinojs/runs/6141133611?check_suite_focus=true
If you check the output of the build step in theses links (scroll up), you can see that the error message by `git log` is mixed with the build command, causing the build to fail.
Fetch all branches by using `fetch-depth: 0`.
EDIT: Also get commit hash from `origin/main` instead of `main`.
Try running any CI tests after this change is merged.
None.
None.
=> Fix broken test suite (Github Actions)

api/storage/storage.cpp
This PR adds a simple functionality, which is setting the Hidden attribute flag on windows to the `.storage` folder, on Linux any file/folder starting with a period is automatically hidden, but on windows you need to set that flag.
- `api/storage/storage.cpp`: Uses [`SetFileAttributes`](https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-setfileattributesa) Function from [`Fileapi.h`](https://docs.microsoft.com/en-us/windows/win32/api/fileapi/) To Set The Hidden Flag of the newly created `.storage` folder.
- Use the [Storage API](https://neutralino.js.org/docs/api/storage/)
None.
None.
=> Hidden folder attribute

api/filesystem/filesystem.cpp, api/filesystem/filesystem.h
Fixes #876 
[WIP]
Update `filesystem.getStats()` function to return last modified time and created time in seconds when called.
To test call the following function:
```
async function displayGetStats() {
try{
let stats = await Neutralino.filesystem.getStats('path_to_file');
console.log('Stats:', stats);
}
catch(e){
console.log(e);
}
}
displayGetStats();
```
=> Update filesystem.getStats(path) to fetch last modified and created time

api/os/os.cpp
I've made a small change to showSaveDialog that allows you to specify an option called `defaultPath`. This can be used for both setting a default directory like this:
```javascript
let entry = await Neutralino.os.showSaveDialog('Open a file', {
filters: [
{name: 'Images', extensions: ['jpg', 'png']},
{name: 'All files', extensions: ['*']}
],
defaultPath: '/home/my/directory/'
});
console.log('You have selected:', entry);
```
and a default filename like this:
```javascript
let entry = await Neutralino.os.showSaveDialog('Open a file', {
filters: [
{name: 'Images', extensions: ['jpg', 'png']},
{name: 'All files', extensions: ['*']}
],
defaultPath: '/home/my/directory/untitled.jpg'
});
console.log('You have selected:', entry);
```
I did submit and close a previous PR that tried to do further …
=> Add ability to set default path and filename on Neutralino.os methods like showSaveDialog()

chrome.cpp
This PR removes the `--enable-automation` Chrome flag.
This removes the "Chrome is being controlled by automated test software" infobar.
This fixes issue #915.
=> Remove --enable-automation Chrome flag to fix #915.

.github/workflows/create_release.yml, .github/workflows/nightly_release.yml, .github/workflows/test_suite.yml, buildzri.config.json, lib/tray/tray.h, scripts/bz.py
Based on #1010, but rebased to latest master.
Therefore it's reviewed best commit-by-commit.
**Note: I did not test if the artifacts are good because my own fork is missing the GitHub tokens.**
I've added cross-compilation to macOS, so we can compile for x64 and arm64 (Apple Silicon aka. M1 / M2) macs regardless of the CI platform.
This also makes CI more robust, as migration to arm based CPUs won't break the CI.
Additionally, we'll bundle the arm64 and x64 binary into a single universal binary (of larger size), so the user doesn't have to worry about picking the appropriate binary (which avoids Rosetta, if possible).
- Remove non-sensical `use_mac_rosetta` from build-script, because rosetta is an emulator at runtime, not a build flag
- Add arch argument to the macOS compiler line, so we …
=> Add cross-compile support for macOS and create universal binary (ARM for Apple Silicon M1 / M2 + x86_64 for Intel based mac)

api/filesystem/filesystem.cpp
See #1053 for more details or sample test code. But this _should_ fix binary data being appended getting corrupted (due to Window EOL.) But this seems to fix my issues where downloaded zip files are corrupted on Windows. :)
- Handle  appending data as binary as well
- Can see the sample code in #1053
None.
None.
=> [#1053] Fix Windows Binary Corruption

api/window/window.cpp, api/window/window.h, lib/webview/webview.h
This was originally implemented in PR #950 which has now been closed. I've updated it to work with the latest working version of the repo.
On Windows if you launch Neutralino with `hidden: true` in the config. A window appears for a split second before disappearing. Quite a few people have expressed a wish to have this changed so that the window never appears with this setting, so this pull request introduces a solution that should work given the conditions.
I tested a lot of solutions before hand. Ideally using SW_HIDE when the window is first created would be the solution, however if you do that, the WebView component always fails to load, with a corrupt connection to it's developer tools.
The changes made in this pull request are all scoped specifically for Windows using `#if …
=> Fixed the popup issue in windows.

server/router.cpp
Currently, a HTTP 404 status code is returned when the file path is invalid, however the message body contains all the global variables instead of a valid error message (Refer to issue #1058 ). With this PR, the router will now check if the file is read successfully before adding content to the response data.
- Check for `fileReaderResult.status` before checking the contents of  `prependData` 
- A suitable message in the response body would be beneficial but I am not sure about the content.
=> Fix: Invalid file path in HTTP request returns global variables

api/window/window.cpp, api/window/window.h, bin/neutralino.config.json, settings.cpp
- Adds `modes.window.x` and `modes.window.y` integer props to config
- Adds config overrides: `--window-x=<int>` and `--window-y=<int>`
=> Setting the window position from app config and CLI

api/filesystem/filesystem.cpp, api/os/os.cpp, buildzri.config.json, lib/tray/tray.h, lib/webview/webview.h, main.cpp, resources.cpp, utils/win/str_conv.cpp
Under Windows, Neutralino doesn't support Unicode, see the linked issues below.  
This pull request should hopefully fix this, by using the Unicode WinApi.
- [GSOC2023 - Support Unicode characters in Neutralinojs Windows version](https://github.com/neutralinojs/gsoc2023#2-support-unicode-characters-in-neutralinojs-windows-version)
- [Issue #613 - UTF-8 not supported in Native API](https://github.com/neutralinojs/neutralinojs/issues/613)
- [Issue #782 - filesystem.readDirectory fails when results would return filenames containing umlauts](https://github.com/neutralinojs/neutralinojs/issues/782)
- [Issue #808 - starter template crashes on windows 10 - error code 3221225477](https://github.com/neutralinojs/neutralinojs/issues/808)
- [Issue #960 - No Unicode support in …
=> Fix Unicode in the Windows version of Neutralino.js

api/os/os.cpp
Fixes a bug on linux  #1115  where the tray icon doesn't after initial call.
Use alternating temporary filenames so tray_update() would work as expected.
=> Fix non-changing of tray icon on linux

lib/webview/webview.h
Intercepting window close in JS leads to wrong memory management when native window is closed (possibly invalid window handle).
I've seen it in debug-builds within VS2019, but it could possibly happen on release.
These are the steps to describe what happens:
- native window X button is clicked by the user
- JS receives the `windowClose` event, does its own tasks and then calls `app.exit()`
- `app.exit()` calls `window::_close(code);`
`window::_close()` function contains the misbehavior:
```C++
// window.cpp
void _close(int exitCode) {
if(nativeWindow) {
nativeWindow->terminate(exitCode);  // <-- THIS CALL IS NON-BLOCKING!
delete nativeWindow;
}
}
// webview.h
void terminate(int exitCode = 0) {
processExitCode = exitCode;
dispatch([=]() {
DestroyWindow(m_window);
});
}
void …
```
=> Fixed memory management issue while closing native Win32 window

lib/tray/tray.h
fix #1128, `char*` can't be cast to `wchar_t*`. this pr added a helper function
=> fix encoding problem in tray menus

api/window/window.cpp, api/window/window.h, bin/neutralino.config.json, buildzri.config.json, lib/webview/webview.h, settings.cpp, spec/config.spec.js
Fixes #396 
- Extends user agent via the `window.extendUserAgentWith` configuration property
- Available as a command-line option: `--window-extend-user-agent-with=<string>`
=> Support extending the default user agent string

spec/runner.js
test runner uses process.arch on mac, like on linux
Run specs/tests on an arm based mac
=> test runner uses process.arch on mac

api/os/os.cpp, helpers.cpp, helpers.h
(https://github.com/neutralinojs/neutralino.js/issues/66)](https://github.com/neutralinojs/neutralino.js/issues/66)
=> showFolderDialog is fixed: forward slashes is provided

api/fs/fs.cpp, bin/resources/js/main_spec.js, spec/filesystem.spec.js
Resolves: #1227 
Provides ability to over write existing files with `filesystem.copy()`
Test case passes:
modifies filesystem.copy() to overwrite existing files as requested in the issue mentioned
- changes to `filesystem.copy()`
- test case added for the same
None.
None.
=> Functionality to overwrite files with `filesystem.copy()`

spec/events.spec.js
This PR adds the following testcases for the events API
- on()
- off()
- dispatch()
- broadcast()
- `cd spec && npm test events`
None.
None.
=> GSoC2024: TestSuite - events API

lib/webview/webview.h
This enables support for transparent windows on Windows.
Resolves #1201.
* Add WS_EX_LAYERED to GWL_EXSTYLE
* Overwrite GWL_STYLE and only keep WS_THICKFRAME, this in effect makes the window borderless, apart from the drag handles for resizing.
* Set the `WEBVIEW2_DEFAULT_BACKGROUND_COLOR` environment variable to make the WebView2 background transparent white.
* Set the initial window size to 8000x8000. There is an issue I haven't been able to figure out where the initial window size of a layered window dictates the active area of the window. This works around it for most cases, as most people don't have monitors with greater than 8k resolution.
Set `"transparent": true` in `neutralino.config.json`.
=> Add transparent windows support on Windows

spec/storage.spec.js
This PR adds test cases to the storage API for better coverage.
- setData()
- getData()
-  getKeys()
- Run `cd spec && npm test storage`
=> GSoC2024: TestSuite - storage API

spec/globalvariables.spec.js
This PR extends the test suite for global variables
- Run `cd spec && npm test globalvariables`
=> GSoC2024: TestSuite - global variables

spec/filesystem.spec.js, spec/os.spec.js
This PR adds test cases for the new version changes
- filesystem.createDirectory()
- filesystem.getRelativePath()
- filesystem.getPathParts()
- os.getEnv()
- os.getPath()
- Run `cd spec && rpm test filesystem`
- Run `cd spec && rpm test os`
=> GSoC2024: TestSuite - version 5.3.0

api/clipboard/clipboard.cpp
It fixes the working of writeImage() function In Windows 11.
Black Image is written to the clipboard.
Image with all the specs is written properly to the clipboard
* The Latest image is the one written in the clipboard
- Added the Alpha Mask and Alpha Shift to the image object in the Read Image Function
- Set the Alpha Mask and Alpha Shift to the image spec in the Write Image Function
async function WriteImage() {
const image = await Neutralino.clipboard.readImage();
console.log(image);
const result = await Neutralino.clipboard.writeImage(image);
console.log(result);
}
=> Fix: Write Image to Clipboard on Windows

lib/webview/webview.h
in certain Windows configurations, the signal expected by "WaitForSingleObject" before closing the application window (when "exitProcessOnClose" is true in neutralino.config.json), is not received. Which creates a freeze lasting from 2sec to 10sec on some machines. #1179 
- Reduced WaitForSingleObject delay
I don't know enough about C++ to delve deeper into the problem. But the next step would be to see why when "exitProcessOnClose" is true, the behavior of the closure changes and blocks at this step.
None.
=> Reduce delay before app closes on windows

settings.cpp
This change will allow the devtools extension to connect when the Neutralino app is in development configuration.
- Flip the conditional statement in `settings.cpp` to `!resources::isBundleMode()`
- Run a frontend library app that requires a devtools connection to patch the HTML file
None.
None.
=> Fix neu devtools extension condition

scripts/bz.py
The bug is fixed 
The issue (SyntaxWarning: invalid escape sequence '\ ') is fixed. By making the string literal raw by adding an r prefix to the triple-quoted string. Hope that solves the bug.
=> commiting bz.py and fixing the bug that caused syntax error/Bxpx6

lib/webview/webview.h, spec/window.spec.js
The `window.getTitle()` function was returning an empty string on the Windows platform, as reported in the [neutralinojs/neutralino.js#123](https://github.com/neutralinojs/neutralino.js/issues/123) repository.
The issue was caused by an incorrect implementation in the `get_title()` function within the `WEBVIEW_EDGE` section of `webview.h`. The function did not handle the string correctly and passed the wrong `HWND` to the `GetWindowText` function, resulting in an empty string being returned.
The implementation of `get_title()` was updated to correctly retrieve the window title & tested on windows.
=> Fix: Ensure window.getTitle() works on Windows platform

server/neuserver.cpp
Closes #957
Closes #1217
Ssssoooo... Windows is a "miracle".
When serving files from `localhost`, any [requests to `localhost` will go through DNS resolve system](https://stackoverflow.com/questions/2386299/running-sites-on-localhost-is-extremely-slow) and will have long Initial Connection time. In my case this time takes 300ms for **each** request on a pretty powerful laptop.
The problem became evident when migrating to my Neutralino.app.mount method when working with local files.
Loading a project on localhost:
See those yellow lines? Each is 300ms+ long and is resolving `localhost` (the Initial Connection stat in DevTools' Network tab.)
Loading the same project on 127.0.0.1:
Changing the hostname also made my app load noticeably faster.
* Neutralino.js will now open applications on …
=> :zap: Host pages from 127.0.0.1 instead of localhost

README.md, api/app/app.cpp, api/app/app.h, errors.cpp, errors.h, server/router.cpp, server/router.h, spec/app.spec.js
Closes #993
Provides a solution to #1291 use case but is not a solution for the `file://` protocol.
This PR adds new methods `Neutralino.app.mount` and `Neutralino.app.unmount` that allow to add and remove filesystem folders on local machine to be included in Neutralino's web server routing.
Calling `Neutralino.app.mount('/sausage', 'C:/Users/CoMiGo/Some Directory');` will make any requests to `/sausage/**` to read and serve files from that folder:
* fetching `/sausage` will try to load `C:/Users/CoMiGo/Some Directory/index.html`
* fetching `/sausage/hello.txt` will try to load `C:/Users/CoMiGo/Some Directory/hello.txt`
* fetching `/not-a-sausage/hello.txt` will try to load a file from the app's resources folder as usual.
Calling `Neutralino.app.unmount('/sausage')` will revert the …
=> ✨ app.mount, app.unmount for hosting files from filesystem

api/clipboard/clipboard.cpp, api/clipboard/clipboard.h, lib/clip/clip.cpp, lib/clip/clip.h, lib/clip/clip_win.cpp, server/router.cpp, spec/clipboard.spec.js
Fixes: #1361 
Added HTML clipboard support to Neutralinojs, enabling rich text and formatted content handling across platforms.
- Implemented HTML clipboard API methods: writeHTML() and readHTML()
- Used Microsoft HTML clipboard format for Windows (Reference: [Microsoft HTML Clipboard Format](https://learn.microsoft.com/en-us/troubleshoot/developer/visualstudio/cpp/language-compilers/add-html-code-clipboard))
- Linux support via native text/html format
- Added comprehensive test suite for HTML clipboard operations
- Windows: Microsoft HTML clipboard format implemented
- Linux: Native text/html format support
- macOS: Native public.html format expected to work, but requires verification as I don't have macOS environment to test it
- Verify HTML clipboard operations by creating a simple …
=> Added HTML Clipboard Support

api/os/os.cpp, api/os/os.h
Related issue: #1373 
- This PR adds support for passing custom environment variables and working directories, which wasn't possible with the current `os.spawnProcess` API.
- Added `SpawnProcessOptions` struct supporting:
- `cwd`: Working directory specification
- `envs`: Custom environment variables
- App developers can simply get the parent process's environment variables using os.getEnvs() if they need:
`Neutralino.os.spawnProcess('my-command', {envs: {...await Neutralino.os.getEnvs(), 'VAR1', '1', ...}});`
**Note:**  This implementation matches Node.js's child_process.exec behavior.
=> Implement environment variable support for spawnProcess

auth/authbasic.cpp
As mentioned in https://github.com/neutralinojs/neutralinojs/issues/1292 neutralino app crashes when the folder does not have write permissions. 
The issue most probably arises from here:
https://github.com/neutralinojs/neutralinojs/blob/4f8c45e3640f8b9ae39b51a862899689a34256e3/auth/authbasic.cpp#L40
There is no error handling mechanism when calling ``filesystem::create_directory`` function which most likely causes the neutralino app to crash. If the exception is handled then possibly the app can be saved from crashing, and the debug message is printed on the console.
- Added error handling to ``filesystem::create_directory`` function call.
Needs testing on windows, i will be testing this on windows and try to simulate the same environment as mentioned in …
=> Added error hadling for insufficient permissions crash when creating /.tmp directory.

api/fs/fs.cpp, helpers.cpp, helpers.h
This PR adds a ``timestamp`` field in the ``watchFile`` event generated by the filesystem ``watcher`` in Neutralinojs. The timestamp follows the ``ISO 8601`` format (``YYYY-MM-DDTHH:mm:ss.sssZ``) and represents the exact time when the file change event occurred.
- Added a timestamp field in the ``watchFile`` event payload, formatted in ``ISO 8601`` UTC (Zulu time).
- added ``getCurrentTimestamp()`` function definition in ``helpers.cpp`` and declaration in ``helpers.h``
- Adds ``timestamp`` field in the json return object.
```json
{
"action": "modified",
"dir": "./resources",
"filename": "changedFile.txt",
"id": 1,
}
```
```json
{
"action": "modified",
"dir": "./resources",
"filename": "changedFile.txt",
"id": 1,
"timestamp": "2025-02-15T04:14:50.385Z"
}
```
> Conversion into local time …
=> Added timestamp field in ``watchFile`` event data. 

server/router.cpp, spec/server.spec.js
Fixes NE_FS_NOPATHE when using `Neutralino.server.mount` with paths that, say, contain cyrillic symbols.
- Use `filesystem::path(CONVSTR(target))` to properly handle paths on Windows
- Add a test case to ensure the method works with non-latin paths on all systems
- `npm run test server`
None.
None.
=> :bug: Windows: Fix NE_FS_NOPATHE errors when using server.mount on a path that contains non-ASCII symbols
