- README.md
Changes as per Issue #69. Done.
> changes done as per issue

- README.md
@shalithasuranga This PR resolves #79
> Fixes stackoverflow typo in readme

- core-windows/src/core/filesystem.cpp
This is for #46 and for windows
> Add success response and clean codes

- core-windows/build.bat
> Improve windows build script

- .github/PULL_REQUEST_TEMPLATE.md
This pull request Fixes https://github.com/neutralinojs/neutralinojs/issues/97 
- Adding PULL_REQUEST_TEMPLATE.md
None.
None.
None.
> Adding simple pull request template

- README.md
Removed Unwanted // at end of README
Issue: #115
> Remove // at end of README

- hackathons/openhack.md
Adds releases header with various versions and providing a link to 1.0.6
> Resolves #95 | Add Release version 1.0.6 to openhack.md

- core-linux/build.sh
- core-linux/src/Socket.cpp
- core-linux/src/settings.cpp
- core-shared/log.cpp
- core-shared/log.h
- core-windows/build.bat
- core-windows/src/settings.cpp
This is a small logging class without any dependencies. It is basically a drop-in replacement for `std::cout`, however it features several log levels and automatically adds the filename and the function name to the output.
Example:
```
void func()
{
INFO() << "Info log";
}
```
Output:
```
INFO [example.cpp:func] Info log
```
- No tests required, since it is very small.
Maybe implementation of additional features if required.
None.
---
<details>
<summary>
<b>IssueHunt Summary</b>
</summary>
This pull request has been submitted to:
- [#134: Introduce a logger for njs server](https://issuehunt.io/repos/138368259/issues/134)
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>
> Add logging class, implement #134.

- README.md
Added contributors using [contributors-img](https://dev.to/lacolaco/introducing-contributors-img-keep-contributors-in-readme-md-gci)
* Added contributors-img anchor tag to `README.md`
View [README.md](https://github.com/AppField/neutralinojs/tree/patch-1#contributors)
None.
None.
> Added contributors to README.md

- core-linux/build.sh
- core-linux/src/cloud/privileges.cpp
- core-linux/src/cloud/privileges.h
- core-linux/src/main.cpp
- core-linux/src/ping/ping.cpp
- core-linux/src/router.cpp
- core-macos/src/cloud/privileges.cpp
- core-macos/src/cloud/privileges.h
- core-macos/src/main.cpp
- core-macos/src/ping/ping.cpp
- core-macos/src/router.cpp
- core-windows/build.bat
- core-windows/src/cloud/privileges.cpp
- core-windows/src/cloud/privileges.h
- core-windows/src/ping/ping.cpp
- core-windows/src/router.cpp
- core-windows/src/serverlistener.cpp
Fixed misspelled work across the code base
- Renamed files, also updated the references to them
> Refactor: Fix "privileges" misspelling

- .github/workflows/cpp_ci.yml
- core-macos/src/core/filesystem.cpp
- core-macos/src/core/include/filesystem.h
- core-macos/src/router.cpp
Fixes ambiguous error on build
> filesystem to fs

- README.md
> Update MacOS build

- core-linux/src/router.cpp
Hello,
Just a simple correction of a typo I found exploring the code.
> Typo correction

- README.md
- core-linux/bin/app/settings.json
- core-linux/build.sh
- core-linux/src/main.cpp
- core-linux/src/webview.h
- dist/app/index.html
- dist/app/settings.json
- neutralino.js/package-lock.json
add borderless window option for Linux 
- set borderlesswindow property to true in settings.json to enable borderless/un-decorated top window
- false for the opposite
Fixes #242
> add borderless window option for linux

- core-windows/build.bat
- core-windows/src/core/filesystem/filesystem.cpp
- core-windows/src/core/filesystem/filesystem.h
- core-windows/src/router.cpp
> Fix build issue on Windows

- api/filesystem/filesystem.cpp
- api/os/os.cpp
- api/window/window.cpp
- build_freebsd.sh
- lib/boxer/boxer_freebsd.cpp
- main.cpp
- platform/freebsd/platform.cpp
- settings.cpp
Fix building on FreeBSD
Adding script `build_freebsd.sh` and set various `#define (__FreeBSD__)`
> Fix compilation on FreeBSD

- README.md
Fixed typo in `readme.md` file
- Just fixed a typo in line 103
- Nothing else
There is no break on code. 
* Read, approve, _presto_
None.
None.
> Typo fixed (line 103)

- README.md
Updated readme for "Application was terminated." error (on Linux) and guide to install on Fedora/RHEL based distros,
> Fedora/RHEL based Linux error fix and install guide

- api/os/os.cpp
This adds a new api function to `os.showDialogOpen` to allow users to add file filters to the dialog so that only certain file types can be selected as requested in #531 and also fixes some formatting issues on Linux and Mac regarding the values returned from os::ExecuteCommand()
- Added a new setting to `os.showDialogOpen` called filter. (Small example below)
- Call `os.showDialogOpen` with `isDirectoryMode` set to `false` and add `filter: ["png", "jpg", "*"]` to the settings. So the call should look like this:
```javascript
let response = await Neutralino.os.showDialogOpen({
title: 'Select a file',
isDirectoryMode: false,
filter: ["png", "jpg", "*"]
});
console.log(`You've selected: ${response.selectedEntry}`);
```
None.
None.
> Added support for file extension filter in File Select dialogs and Fixed some Linux/MacOS bugs

- README.md
fixed bad link (404) in readme.md - "master" -> "main"
issue found using tool: https://github.com/MrCull/GitHub-Repo-ReadMe-Dead-Link-Finder
Doc
Click link in preview
None.
None.
> fixed bad link (404) in readme.md - "master" -> "main"

- .github/workflows/codeql_analysis.yml
- .github/workflows/create_release.yml
- .github/workflows/test_suite.yml
- build_linux.sh
- lib/tray/tray.h
Uses the ayatana appindicator which fixes the linux build on debian 11.
- replaces appindicator with ayatana-appindicator.
None.
None.
> Use ayatana appindicator

- .github/workflows/test_suite.yml
> Run test suite on Windows OS

- README.md
> Updated README.md to show different logo for dark and light mode respectively

- .github/workflows/codeql_analysis.yml
- .github/workflows/create_release.yml
- .github/workflows/nightly_release.yml
Closes #1135
Closes #1118
Untested.
> Update GitHub Actions external actions to their latest versions

- api/filesystem/filesystem.cpp
Resolves #1164 
-  using `std::filesystem` for creating or removing directories
- changed `createDirectory()` function in filesystem.cpp
- changes `removeDirectory()` functoin in filesystem.cpp
- test already exists
None.
None.
> added: filesystem for creating and removing nested directories

- api/clipboard/clipboard.cpp
- spec/clipboard.spec.js
- Added a method called `clearClipboard()` to clear the clipboard in the `clipboard api`
- added a new function to clear clipboard
- Run specs/tests I have added tests
None.
None.
> feat: added clearClipboard() method to the clipboard api

- api/clipboard/clipboard.cpp
- api/clipboard/clipboard.h
This PR adds a missing semicolon and exposes `clipboard.clear()` method in `cliboard.h`
- adding semicolon
- exposing `clipboard.clear()` function in `clipboard.h`
None.
None.
> adding missing semicolon and exposing `clipboard.clear()` method in `cliboard.h`

- api/window/window.cpp
- api/window/window.h
- lib/webview/webview.h
Fixes #1202 
Binary size was reduced from ~ 1.7 -> ~ 1.6 on Linux
> Cleaned up webview lib by removing unused function binding logic

- spec/clipboard.spec.js
this PR adds a test case to the newly added clipboard.clear() method
- added a testcase in `clipboard.spec.js`
- Run `cd spec`
- Run `npm test clipboard`
None.
None.
> added test case for clipboard.clear()

- spec/clipboard.spec.js
This PR adds more test cases for clipoard API including some edge cases
- added test cases for clipboard api
None.
None.
> More test cases for clipboard API including some edge cases

- api/os/os.cpp
- api/window/window.cpp
This pull request aims to fix an issue where the application window wouldn't properly come to the foreground on Windows systems after being minimized. The previous implementation lacked proper handling to ensure the window regained focus reliably, especially on newer versions of Windows.
solved --> https://github.com/neutralinojs/neutralinojs/issues/1232 
- **Refined Window Show Logic**: Updated the `show()` function to include additional checks and actions specifically tailored for Windows platforms.
- Restores the window if it was minimized before attempting to bring it to the foreground.
- Utilizes `SetWindowPos` to adjust the window z-order, ensuring it's visible to the user.
- Attempts to bring the window to the foreground using `SetForegroundWindow`.
- Introduces a user-friendly …
> Fixing bug of Minimized app display & window.show()  

- spec/debug.spec.js
This PR adds additional testcases for debug API for a better test coverage
Following testcases have been added
log()
None.
None.
> TestSuite: debug API

- spec/filesystem.spec.js
- spec/index.js
- `createDirectory()`
- `remove()`
- `writeFile()`
- `appendFile()`
- `readFile()`
- `writeBinaryFile()`
- `appendBinaryFile()`
- `readBinaryFile()`
- `openFile()`
- `updateOpenedFile()`
- `getOpenedFileInfo()`
- `readDirectory()`
- `copy()`
- `move()`
- `getStats()`
- changed mocha timeout to 22000ms since some tests were failing with 20000ms timeout
- `cd spec && npm test filesystem`
None.
None.
> GSoC2024: Test Suite - filesystem API

- spec/extensions.spec.js
This PR adds testcases for the extensions API
- getStats()
- dispatch()
- broadcast()
- `cd spec && npm test extensions`
None.
None.
> GSoC2024: Test Suite - extensions API

- spec/clipboard.spec.js
This PR adds test cases to clipboard API for better coverage
- writeText()
- readText()
- writeImage()
- readImage()
- clear()
- getFormat()
- Run `cd spec && npm test clipboard`
None.
None.
> GSoC2024: TestSuite - clipboard API

- _gsoc-win7-support/README.md
- Created `_gsoc-win7-support` directory to organize documentation related to Windows 7 support.
- Added `README.md` to document the issues, solutions, and progress related to Windows 7 support.
- Will include findings and documentation in further PRs.
- Continue documenting further findings and issues encountered.
- Update `README.md` with additional solutions and progress.
- Submit additional pull requests as necessary to address further compatibility issues.
None.
> Add _gsoc-win7-support folder with README.md for Windows 7 support documentation

- spec/os.spec.js
This PR adds test cases to the OS API for better coverage.
-  execCommand()
- spawnProcess()
- getSpawnedProcess()
- updateSpawnedProcess()
- getEnv()
- getEnvs
- showNotification()
- setTray()
- open()
- getPath()
- Run `cd spec && npm test os`
None.
None.
> GSoC2024: TestSuite - os API

- spec/window.spec.js
- setTitle()
- getTitle()
- maximize()
- isMaximized()
- unmaximize()
- setFullScreen()
- exitFullScreen()
- show()
- hide()
- move()
- setAlwaysOnTop()
- Run `cd spec && npm test window`
None.
None.
> GSoC2024: TestSuite - window API

- helpers.cpp
This PR fixes the ``generateToken()`` method in ``helpers.cpp`` the generated token is used for authentication. The current implementation of this function generates the same token again and again as mentioned in this issue https://github.com/neutralinojs/neutralinojs/issues/1367 The issue was the way ``srand(time(NULL))`` was placed or being used, but this method for random generation is old and outdated and should not be used.
Fixes: #1367 
- Get rid of ``srand(time(NULL))``
- Used standard provided [Mersenne Twister](https://en.wikipedia.org/wiki/Mersenne_Twister) for random generation
The testing is not as straight forward, there are no tests available in ``/spec`` folder to test the efficiency of ``generateToken`` function, but you can view the comparison by running the old …
> Fixed token generation in generateToken() function in helpers.cpp

- api/window/window.cpp
- api/window/window.h
- server/router.cpp
Summary
This PR introduces window.setMainMenu(menu), a new API function for creating native application menus in Neutralinojs. Previously, Neutralinojs only supported tray menus (os.setTray()), forcing developers to use JavaScript-based keyboard shortcuts or HTML/CSS-based menu UIs.
With this PR, developers can now define a native menu structure and handle menu clicks inside their Neutralino apps.
**Added window.setMainMenu() API function**
- Allows developers to define a structured menu via JSON.
- Uses platform-specific APIs to render native menus.
- Provides event handling for menu item clicks (mainMenuItemClicked).
**Developers can define a menu structure in JavaScript:**
```
async function setupMainMenu() {
let menu = [
{
text: "File",
menuItems: [
{ id: "OPEN", text: "Open" },
{ …
```
> Add window.setMainMenu() for Native Main Menu Support
